package game.Capable;

/**
 * Interface to represent Actor that is killable and able to generate rune after death.
 * @author Chew Xin Ning 32693974
 * @version 1.0
 */
public interface Killable {

    /**
     * Method to obtain the rune generated by the actor after death.
     * @return random number of runes
     */
    int getRune();
}
